// <auto-generated />
namespace TicketingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addPromotion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPromotion));
        
        string IMigrationMetadata.Id
        {
            get { return "202303120743345_addPromotion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
