// <auto-generated />
namespace TicketingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "202303140358185_userProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
